name: My CICD Pipeline in GitHub Actions

on:
  push:
    branches: main

jobs: 
  build:
    runs-on: ubuntu-latest

steps: 
   - uses: actions/checkout@v4

   -name: My first step
   run: | 
    echo "This is DevOps Faaiq"
    uname -a
   
